import { env } from "@/env";
import {
  ENUM_CHECKIN_STATUS,
  ENUM_EVENT_TYPE,
  ENUM_LGND_FUNCAO,
  ENUM_PAYMENT_STATUS,
  ENUM_STATUS,
  ENUM_USER,
} from "./enum";
// List of routes that don't have orgSlug and should be public
export const excludedRoutes = [
  "",
  // 'manada',
  "identificacao",
  "api",
  "_next",
  "auth",
  "criar-organizacao",
  "criar-evento",
  "perguntas-frequentes",
];

export const URL_CEP_API = `https://viacep.com.br/ws/`;

export const stringToBoolean = (value: string): boolean => value === `true`;
export const booleanToString = (value: boolean): "true" | "false" =>
  value === true ? `true` : `false`;

export const FEATURE_FLAG_SHOW_CREDITCARD = stringToBoolean(
  env.NEXT_PUBLIC_SHOW_CREDIT_CARD ?? "",
);

export const FEATURE_FLAG_SHOW_CREDITCARD_OPTION_PARTICIPANTE = stringToBoolean(
  env.NEXT_PUBLIC_SHOW_CREDIT_CARD_PARTICIPANTE ?? "",
);

export const NEXT_PUBLIC_SHOW_REGISTER_CANCELED_DASHBOARD = stringToBoolean(
  env.NEXT_PUBLIC_SHOW_REGISTER_CANCELED_DASHBOARD ?? "",
);

export const FEATURE_FLAG_SHOW_CREDITCARD_OPTION_SERVIR = stringToBoolean(
  env.NEXT_PUBLIC_SHOW_CREDIT_CARD_SERVIR ?? "",
);

export const FEATURE_FLAG_SECRET_LINK = stringToBoolean(
  env.NEXT_PUBLIC_SECRET_LINK ?? "",
);

export const getLinkInscritosOrLgndServir = (pathname: string) => {
  return pathname.includes("participantes") ? "participantes" : "servir";
};

export const CUSTOM_ALPHABET_CHECK_IN_CODE = {
  alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  size: 6,
};

export const ITOP = {
  name: "Inscrições TOP",
  short_name: "iTOP",
  whatsapp_suporte: "67991386745", // número bussiness do iTOP
  demoScheduleWhatsApp:
    "Gostaria de agendar uma demonstração no iTOP - Sistema de Gerenciamento de Inscrições e Adm do TOP",
  whatsapp_demo: "67992275455", // número pessoal do Roberson
  email_suporte: "inscricoestop@gmail.com",
  site: "https://inscricoestop.com.br",
  description: "Sistema de Gerenciamento de Inscrições e Adm dos TOPs",
  // TODO: ideal seria pegar o NR do TOP em questão
  whatsapp_text_support_participar: `Quero fazer minha inscrição no Evento`,
  whatsapp_text_support_servir: "Preciso de ajuda para servir no Evento",
  mochila: "https://www.legendariosms.com/mochila",
  imageBaseUrl: "https://www.inscricoestop.com.br",
  fee: 5, // 5% de taxa cobrada para cada inscrição concluida
  cardFee: {
    1: 5.61, // parcela 1 | taxa: 5.61
    2: 7.03,
    3: 7.86,
    4: 8.69,
    5: 10.52,
    6: 11.35,
    7: 12.55,
    8: 13.37,
    9: 14.19,
    10: 15.01,
    11: 15.83,
    12: 16.65,
  },
  register_politic: [
    {
      title: "Cancelamento da Inscrição",
      roles: [
        "- Até 7 dias após a compra: reembolso de 100% do valor pago.",
        "- Após 7 dias da compra: reembolso de 90% do valor pago aplicando multa de 10%.",
        "- No dia ou após o evento não haverá cancelamento ou até mesmo estorno do valor da inscrição.",
      ],
    },
    {
      title: "Transferência de Titularidade",
      roles: [
        "- Deve ser solicitada até 48 horas antes do início do evento.",
        "- Será realizada mediante pagamento de taxa administrativa.",
      ],
    },
    {
      title: "Transferência para Outro Evento",
      roles: [
        "- Não é permitida a transferência para eventos futuros.",
        "- Em caso de desistência sem transferência, aplica-se a política de cancelamento.",
      ],
    },
  ],
};

export const ASAAS = {
  // baseado no calculo de juros com antecipação, tem que se cobrado 300 reais a mais para que na antecipação tenha 1500
  fee_credit_card_participante: 300,
  // baseado no calculo de juros com antecipação, tem que se cobrado 100 reais a a mais para quem for servir e pagar no cartão
  fee_credit_card_servir: 100,
};

export const yesOrNoOptions = [
  { label: "Sim", value: "true" },
  { label: "Não", value: "false" },
];

export const countries = [
  { label: "Brasil", value: "BR" },
  { label: "Paraguai", value: "PY" },
  { label: "Bolívia", value: "BO" },
  { label: "Estados Unidos", value: "US" },
];

export const allowedCountry = {
  codes: ["55", "595", "591", "58"], // Brasil, Paraguai, Bolívia, Venezuela
  countries: ["br", "py", "bo", "ve"],
};

export const countryCodeMap: { [key: string]: string } = {
  "55": "BR", // Brasil
  "595": "PY", // Paraguai
  "591": "BO", // Bolívia
  "58": "VE", // Venezuela
};

export const familiaOptions = [
  "Nenhum",
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
]; // we don't use 13

export const funcoesLgndOptions = [
  { value: "null", label: "Nenhum" },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_ADM, label: "Coordenador Adm" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_ADM, label: "Sub Coord Adm" },
  { value: ENUM_LGND_FUNCAO.ADM, label: "Adm" },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_AQUAMAN, label: "Coordenador Aquaman" },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_AQUAMAN,
    label: "Sub Coord Aquaman",
  },
  {
    value: ENUM_LGND_FUNCAO.AQUAMAN,
    label: "Aquaman",
  },
  {
    value: ENUM_LGND_FUNCAO.COORDENADOR_COMUNICACAO,
    label: "Coordenador Comunicação",
  },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_COMUNICACAO,
    label: "Sub Coord Comunicação",
  },
  {
    value: ENUM_LGND_FUNCAO.COMUNICACAO,
    label: "Comunicação",
  },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_DIRETOR, label: "Coordenador Diretor" },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_DIRETOR,
    label: "Sub Coord Diretor",
  },
  {
    value: ENUM_LGND_FUNCAO.DIRETOR,
    label: "Diretor",
  },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_EVENTOS, label: "Coordenador Eventos" },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_EVENTOS,
    label: "Sub Coord Eventos",
  },
  {
    value: ENUM_LGND_FUNCAO.EVENTOS,
    label: "Eventos",
  },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_HAKUNA, label: "Coordenador Hakuna" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_HAKUNA, label: "Sub Coord Hakuna" },
  { value: ENUM_LGND_FUNCAO.HAKUNA, label: "Hakuna" },
  {
    value: ENUM_LGND_FUNCAO.COORDENADOR_INTERCESSAO,
    label: "Coordenador Intercessão",
  },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_INTERCESSAO,
    label: "Sub Coord Intercessão",
  },
  {
    value: ENUM_LGND_FUNCAO.INTERCESSAO,
    label: "Intercessão",
  },
  {
    value: ENUM_LGND_FUNCAO.COORDENADOR_LOGISTICA,
    label: "Coordenador Logística",
  },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_LOGISTICA,
    label: "Sub Coord Logística",
  },
  {
    value: ENUM_LGND_FUNCAO.LOGISTICA,
    label: "Logística",
  },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_MIDIA, label: "Coordenador Mídia" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_MIDIA, label: "Sub Coord Mídia" },
  { value: ENUM_LGND_FUNCAO.MIDIA, label: "Mídia" },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_PATRON, label: "Coordenador Patron" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_PATRON, label: "Sub Coord Patron" },
  { value: ENUM_LGND_FUNCAO.PATRON, label: "Patron" },
  {
    value: ENUM_LGND_FUNCAO.COORDENADOR_PREDICANTE,
    label: "Coordenador Predicante",
  },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_PREDICANTE,
    label: "Sub Coord Predicante",
  },
  {
    value: ENUM_LGND_FUNCAO.PREDICANTE,
    label: "Predicante",
  },
  {
    value: ENUM_LGND_FUNCAO.COORDENADOR_SEGURANCA,
    label: "Coordenador Segurança",
  },
  {
    value: ENUM_LGND_FUNCAO.SUB_COORD_SEGURANCA,
    label: "Sub Coord Segurança",
  },
  {
    value: ENUM_LGND_FUNCAO.SEGURANCA,
    label: "Segurança",
  },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_TARZAN, label: "Coordenador Tarzan" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_TARZAN, label: "Sub Coord Tarzan" },
  { value: ENUM_LGND_FUNCAO.TARZAN, label: "Tarzan" },
  { value: ENUM_LGND_FUNCAO.COORDENADOR_VOZ, label: "Coordenador Voz" },
  { value: ENUM_LGND_FUNCAO.SUB_COORD_VOZ, label: "Sub Coord Voz" },
  { value: ENUM_LGND_FUNCAO.VOZ, label: "Voz" },
];

export const statusOptions = [
  { value: ENUM_STATUS.CONFIRMADA, label: "Confirmada" },
  { value: ENUM_STATUS.AGUARDANDO_PAGAMENTO, label: "Aguardando pagamento" },
  { value: ENUM_STATUS.INSCREVENDO, label: "Inscrevendo" },
  {
    value: ENUM_STATUS.CANCELADA_PELO_CLIENTE,
    label: "Cancelada pelo cliente",
  },
  {
    value: ENUM_STATUS.CANCELADA_TEMPO_EXPIRADO,
    label: "Tempo expirado",
  },
];

export const biotipoOptions = [
  {
    value: "corpo-musculoso-baixa-gordura",
    label: "Corpo musculoso, baixa gordura",
  },
  { value: "sobrepeso-sedentario", label: "Sobrepeso, sedentário" },
  { value: "sobrepeso-ativo", label: "Sobrepeso, ativo" },
  { value: "fisiculturista", label: "Fisiculturista" },
  { value: "magro-atletico", label: "Magro atlético" },
  { value: "magro-sedentario", label: "Magro sedentário" },
  {
    value: "condicionamento-fisico-equilibrado",
    label: "Condicionamento físico equilibrado",
  },
];

export const howKnowLegendsOptions = [
  { value: "amigo", label: "Amigo(s)" },
  { value: "celula", label: "Célula" },
  { value: "midias", label: "Mídias" },
  { value: "outros", label: "Outros" },
];

export const vinculoOptions = [
  { value: "Esposa", label: "Esposa" },
  { value: "Filho(a)", label: "Filho(a)" },
  { value: "Pai/Mãe", label: "Pai/Mãe" },
  { value: "Amigo(a)", label: "Amigo(a)" },
  { value: "Outros", label: "Outros" },
];

export const shirtSizesOptions = [
  { value: "PPP", label: "PPP" },
  { value: "PP", label: "PP" },
  { value: "P", label: "P" },
  { value: "M", label: "M" },
  { value: "G", label: "G" },
  { value: "GG", label: "GG" },
  { value: "2GG", label: "2GG" },
  { value: "3GG", label: "3GG" },
  { value: "4GG", label: "4GG" },
  { value: "5GG", label: "5GG" },
];

export const shirtSizesREM = [
  "PP",
  "P",
  "M",
  "G",
  "GG",
  "G1",
  "G2",
  "G3",
  "G4",
  "G5",
];

export const roleOptions = [
  {
    value: ENUM_USER.SUPER_ADMIN,
    label: "Super Administrador",
  },
  {
    value: ENUM_USER.ADMIN,
    label: "Administrador",
  },
  {
    value: ENUM_USER.HAKUNA,
    label: "Hakuna",
  },
  {
    value: ENUM_USER.CHECKIN,
    label: "Check-in",
  },
  {
    value: ENUM_USER.LADIES,
    label: "LADIES",
  },
  {
    value: ENUM_USER.USER,
    label: "Usuário comum",
  },
];

export const paymentStatusOptions = [
  {
    value: ENUM_PAYMENT_STATUS.PAGAMENTO_CARTAO_PENDENTE,
    label: "Cartão pendente",
  },
  {
    value: ENUM_PAYMENT_STATUS.PAGAMENTO_CARTAO_CONCLUIDO,
    label: "Cartão concluído",
  },
  {
    value: ENUM_PAYMENT_STATUS.CREDIT_CARD_PAYMENT_COMPLETED,
    label: "Cartão concluído",
  },
  {
    value: ENUM_PAYMENT_STATUS.CREDIT_CARD_PAYMENT_COMPLETED,
    label: "Cartão Concluído",
  },
  { value: ENUM_PAYMENT_STATUS.CHARGE_COMPLETED, label: "PIX concluído" },
  { value: ENUM_PAYMENT_STATUS.CHARGE_EXPIRED, label: "PIX expirado" },
  {
    value: ENUM_PAYMENT_STATUS.TRANSACTION_REFUND_RECEIVED,
    label: "Estornada",
  },
  { value: ENUM_PAYMENT_STATUS.GRATUITO, label: "Gratuito" },
];

export const registerStatusMap: Record<ENUM_STATUS, string> = {
  [ENUM_STATUS.CONFIRMADA]: "Confirmada",
  [ENUM_STATUS.AGUARDANDO_PAGAMENTO]: "Aguardando Pagamento",
  [ENUM_STATUS.INSCREVENDO]: "Inscrevendo",
  [ENUM_STATUS.CANCELADA_PELO_CLIENTE]: "Cancelada",
  [ENUM_STATUS.CANCELADA_TEMPO_EXPIRADO]: "Tempo Expirado",
};

export const checkinStatusMap: Record<ENUM_CHECKIN_STATUS, string> = {
  [ENUM_CHECKIN_STATUS.WAITING_FOR_DOCUMENTS]: "Aguardando",
  [ENUM_CHECKIN_STATUS.DOCUMENTS_SENT]: "Enviado",
  [ENUM_CHECKIN_STATUS.INVALID_DOCUMENTS]: "Inválido",
  [ENUM_CHECKIN_STATUS.VALID_DOCUMENTS]: "Válido",
};

export const checkinStatusOptions = [
  { value: "null", label: "Termo não enviado" },
  { value: ENUM_CHECKIN_STATUS.WAITING_FOR_DOCUMENTS, label: "Aguardando" },
  { value: ENUM_CHECKIN_STATUS.DOCUMENTS_SENT, label: "Enviado" },
  { value: ENUM_CHECKIN_STATUS.INVALID_DOCUMENTS, label: "Inválido" },
  { value: ENUM_CHECKIN_STATUS.VALID_DOCUMENTS, label: "Válido" },
];

export const eventTypeMap: Record<ENUM_EVENT_TYPE, string> = {
  [ENUM_EVENT_TYPE.LEGENDARIOS]: "TOP",
  [ENUM_EVENT_TYPE.REM]: "REM",
  [ENUM_EVENT_TYPE.LEGADO_FILHA]: "LEGADO FILHA",
  [ENUM_EVENT_TYPE.LEGADO_FILHO]: "LEGADO FILHO",
  [ENUM_EVENT_TYPE.MANADADAY]: "MANADA DAY",
};

export const paymentStatusMap: Record<ENUM_PAYMENT_STATUS, string> = {
  [ENUM_PAYMENT_STATUS.CHARGE_COMPLETED]: "Pago",
  [ENUM_PAYMENT_STATUS.CREDIT_CARD_PAYMENT_COMPLETED]: "Pago",
  [ENUM_PAYMENT_STATUS.PAGAMENTO_CARTAO_CONCLUIDO]: "Pago",
  [ENUM_PAYMENT_STATUS.GRATUITO]: "Gratuito",
  [ENUM_PAYMENT_STATUS.CHARGE_CREATED]: "Pendente",
  [ENUM_PAYMENT_STATUS.CHARGE_EXPIRED]: "Cobrança Expirada",
  [ENUM_PAYMENT_STATUS.PAGAMENTO_CARTAO_PENDENTE]: "Pendente",
  [ENUM_PAYMENT_STATUS.TRANSACTION_REFUND_RECEIVED]: "Reembolsado",
};

export const MASK_PATTERN = {
  phone: "(99)99999-9999",
  cpf: "999.999.999-99",
  cnpj: "99.999.999/9999-99",
  date: "99/99/9999",
  cep: "99.999-999",
  qtdFilhos: "99",
};

export const VISIBLE_COLUMNS = {
  inscritos: [
    "index",
    "actions",
    "createdAt",
    "status",
    "nome",
    "celular",
    "email",
    "igreja",
    "cpf",
    "estadoCivil",
    "temFilhos",
    "qtdFilhos",
    "peso",
    "altura",
    "imc",
    "rua",
    "ruaNumero",
    "ruaComplemento",
    "estado",
    "bairro",
    "cidade",
    "cep",
    "comoConheceuLegendarios",
    "quemConvidou",
    "nomeContatoEmergencia",
    "emailContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "possuiPlanoSaude",
    "nomePlanoSaude",
    "possuiAlergia",
    "possuiDiabetes",
    "possuiConvulsoes",
    "possuiDesmaios",
    "possuiProblemasCardiacos",
    "possuiDisturbiosAlimentares",
    "possuiProblemasRespiratorios",
    "cuidadosPsiquiatricos",
    "medicacaoDepressao",
    "possuiProblemasMusculoesqueleticos",
    "doencaOuCondicao",
    "medicacoes",
    "outrasInformacoesMedicas",
    "linkSecreto",
    "pagamento_couponValue",
  ],
  familia: [
    "nome",
    "familia",
    "saude",
    "idade",
    "imc",
    "classificacaoIMC",
    "igreja",
    "cidade",
    "nomeContatoEmergencia",
    "tipoVinculoContatoEmergencia",
  ],
  cartas: [
    "actions",
    "cartas_obs",
    "cartas_recebida",
    "cartas_contato_valido",
    "nome",
    "nomeContatoCartas",
    "celularContatoCartas",
    "nomeContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "celularContatoEmergencia",
  ],
  lgndServir: [
    "index",
    "actions",
    "createdAt",
    "status",
    "nrLgnd",
    "nome",
    "celular",
    "email",
    "lgndCertificado",
    "igreja",
    "igrejaPastor",
    "cpf",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "estadoCivil",
    "rua",
    "ruaNumero",
    "ruaComplemento",
    "estado",
    "bairro",
    "cidade",
    "cep",
    "nomeContatoEmergencia",
    "emailContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "linkSecreto",
  ],
  ladies: [
    "checkin",
    "familia",
    "nome",
    "nomeContatoCartas",
    "celularContatoCartas",
    "nomeContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "emailContatoEmergencia",
    "cidade",
    "igreja",
    "igrejaPastor",
  ],
  checkinLgnd: [
    "actions",
    "caravana",
    "checkin",
    "checkinStatus",
    "nome",
    "lgnd_funcao",
    "familia",
    // "vehicleId",
    "lgndCertificado",
    "nrLgnd",
    "check_obs",
    "cpf",
    "celular",
    "cidade",
    "igreja",
    "igrejaPastor",
    "pagamento_status",
    "pagamento_couponValue",
    "obs",
  ],
  checkinParticipantes: [
    "actions",
    "checkin",
    "checkinStatus",
    "familia",
    // "vehicleId",
    "caravana",
    "saude",
    "nome",
    "check_obs",
    "cpf",
    "celular",
    "cidade",
    "igreja",
    "igrejaPastor",
    "pagamento_status",
    "pagamento_couponValue",
    "obs",
  ],
  bone: [
    "actions",
    "familia",
    "nrLgnd",
    "nome",
    "tamanhoFarda",
    "cpf",
    "email",
    "celular",
    "cidade",
    "igreja",
    "igrejaPastor",
    "check_obs",
    "obs",
  ],
  hakuna: ["actions", "saude", "familia", "nome", "saude_obs"],
  inscritosRem: [
    "index",
    "actions",
    "createdAt",
    "status",
    "familia",
    "nrRem",
    "nrLgnd",
    "nome",
    "celular",
    "email",
    "cpf",
    "dataNascimento",
    "spouseName",
    "spousePhoneNumber",
    "spouseEmail",
    "spouseCPF",
    "spouseBirthDate",
    "womanTshirtSize",
    "manTshirtSize",
    "igreja",
    "igrejaPastor",
    "cep",
    "rua",
    "ruaNumero",
    "estado",
    "bairro",
    "cidade",
    "hasHealthIssues",
    "healthIssuesDescription",
    "isPregnant",
    "linkSecreto",
    "pagamento_couponValue",
  ],
  lgndServirRem: [
    "index",
    "actions",
    "createdAt",
    "status",
    "nrRem",
    "nrLgnd",
    "nome",
    "cpf",
    "nrLgnd",
    "celular",
    "email",
    "dataNascimento",
    "spouseName",
    "spouseCPF",
    "spousePhoneNumber",
    "spouseEmail",
    "igreja",
    "igrejaPastor",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "cep",
    "rua",
    "ruaNumero",
    "bairro",
    "cidade",
    "womanTshirtSize",
    "manTshirtSize",
    "linkSecreto",
  ],
  checkinParticipantesRem: [
    "actions",
    "checkin",
    "checkinStatus",
    "familia",
    "nrRem",
    "nrLgnd",
    "nome",
    "cpf",
    "manTshirtSize",
    "spouseName",
    "spouseCPF",
    "womanTshirtSize",
    "isPregnant",
    "check_obs",
    "celular",
    "spousePhoneNumber",
    "cidade",
    "igreja",
    "igrejaPastor",
    "obs",
  ],
  checkinLgndRem: [
    "actions",
    "checkin",
    "checkinStatus",
    "nrRem",
    "nrLgnd",
    "nome",
    "cpf",
    "spouseName",
    "spouseCPF",
    "womanTshirtSize",
    "manTshirtSize",
    "check_obs",
    "celular",
    "spousePhoneNumber",
    "cidade",
    "igreja",
    "igrejaPastor",
    "obs",
  ],
  boneRem: [
    "actions",
    "familia",
    "nrRem",
    "nome",
    "cpf",
    "manTshirtSize",
    "spouseName",
    "spouseCPF",
    "womanTshirtSize",
    "celular",
    "spousePhoneNumber",
    "cidade",
    "igreja",
    "igrejaPastor",
    "check_obs",
    "obs",
  ],
  familiaRem: [
    "index",
    "nome",
    "cpf",
    "idade",
    "spouseName",
    "spouseCPF",
    "spouseAge",
    "familia",
    "igreja",
    "cidade",
    "nomeContatoEmergencia",
    "tipoVinculoContatoEmergencia",
  ],
  // Add more pages as needed
};

export const VISIBLE_FIELDS_SIDE_TABLE = {
  inscritos: [
    "status",
    "tipoInscricao",
    "nome",
    "celular",
    "email",
    "dataNascimento",
    "igreja",
    "cpf",
    "estadoCivil",
    "temFilhos",
    "qtdFilhos",
    "peso",
    "altura",
    "imc",
    "rua",
    "ruaNumero",
    "ruaComplemento",
    "estado",
    "bairro",
    "cidade",
    "cep",
    "comoConheceuLegendarios",
    "quemConvidou",
    "nomeContatoEmergencia",
    "emailContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "possuiPlanoSaude",
    "nomePlanoSaude",
    "possuiAlergia",
    "possuiDiabetes",
    "possuiConvulsoes",
    "possuiDesmaios",
    "possuiProblemasCardiacos",
    "possuiDisturbiosAlimentares",
    "possuiProblemasRespiratorios",
    "cuidadosPsiquiatricos",
    "medicacaoDepressao",
    "possuiProblemasMusculoesqueleticos",
    "doencaOuCondicao",
    "medicacoes",
    "outrasInformacoesMedicas",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "metodo_pagamento",
  ],
  inscritosRem: [
    "status",
    "tipoInscricao",
    "nome",
    "cpf",
    "celular",
    "email",
    "dataNascimento",
    "spouseName",
    "spouseCPF",
    "spousePhoneNumber",
    "spouseEmail",
    "spouseBirthDate",
    "womanTshirtSize",
    "manTshirtSize",
    "igreja",
    "igrejaPastor",
    "cep",
    "rua",
    "ruaNumero",
    "estado",
    "bairro",
    "cidade",
    "hasHealthIssues",
    "healthIssuesDescription",
    "isPregnant",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "metodo_pagamento",
  ],
  lgndServir: [
    "status",
    "tipoInscricao",
    "nome",
    "celular",
    "email",
    "dataNascimento",
    "igreja",
    "cpf",
    "estadoCivil",
    "rua",
    "ruaNumero",
    "ruaComplemento",
    "estado",
    "bairro",
    "cidade",
    "cep",
    "nomeContatoEmergencia",
    "emailContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "metodo_pagamento",
  ],
  lgndServirRem: [
    "status",
    "tipoInscricao",
    "nrLgnd",
    "nome",
    "cpf",
    "celular",
    "email",
    "dataNascimento",
    "spouseName",
    "spouseCPF",
    "spousePhoneNumber",
    "spouseEmail",
    "spouseBirthDate",
    "womanTshirtSize",
    "manTshirtSize",
    "igreja",
    "igrejaPastor",
    "cep",
    "rua",
    "ruaNumero",
    "estado",
    "bairro",
    "cidade",
    "hasHealthIssues",
    "healthIssuesDescription",
    "isPregnant",
    "pagamento_status",
    "pagamento_data",
    "pagamento_couponValue",
    "metodo_pagamento",
  ],
  hakuna: [
    "nome",
    "celular",
    "email",
    "igreja",
    "cpf",
    "dataNascimento",
    "estadoCivil",
    "rua",
    "ruaNumero",
    "ruaComplemento",
    "estado",
    "bairro",
    "cidade",
    "cep",
    "nomeContatoEmergencia",
    "celularContatoEmergencia",
    "tipoVinculoContatoEmergencia",
    "peso",
    "altura",
    "imc",
    "biotipo",
    "possuiPlanoSaude",
    "nomePlanoSaude",
    "possuiAlergia",
    "possuiDiabetes",
    "possuiConvulsoes",
    "possuiDesmaios",
    "possuiProblemasCardiacos",
    "possuiDisturbiosAlimentares",
    "possuiProblemasRespiratorios",
    "cuidadosPsiquiatricos",
    "medicacaoDepressao",
    "possuiProblemasMusculoesqueleticos",
    "doencaOuCondicao",
    "medicacoes",
    "outrasInformacoesMedicas",
  ],
};

export const labelsFinancialReportParticipantAndServeByEventType = {
  [ENUM_EVENT_TYPE.LEGENDARIOS]: {
    participant: "Participante",
    serveCertificate: "Servir com Certificado",
    serveNotCertificate: "Servir sem Certificado",
  },
  [ENUM_EVENT_TYPE.REM]: {
    participant: "Participante",
    serveCertificate: "Servir que não comprou camiseta",
    serveNotCertificate: "Servir que comprou camiseta",
  },
  [ENUM_EVENT_TYPE.LEGADO_FILHA]: {
    participant: "",
    serveCertificate: "",
    serveNotCertificate: "",
  },
  [ENUM_EVENT_TYPE.LEGADO_FILHO]: {
    participant: "",
    serveCertificate: "",
    serveNotCertificate: "",
  },
  [ENUM_EVENT_TYPE.MANADADAY]: {
    participant: "Ingressos",
    serveCertificate: "",
    serveNotCertificate: "",
  },
};

export const fieldHeaderLabelMap: Record<string, string> = {
  createdAt: "Data Inscrição",
  spouseCPF: "Esposa CPF",
  spouseName: "Esposa Nome",
  spouseEmail: "Esposa E-mail",
  spousePhoneNumber: "Esposa Celular",
  spouseBirthDate: "Esposa Nascimento",
  spouseAge: "Esposa Idade",
  womanTshirtSize: "Camiseta Esposa",
  manTshirtSize: "Camiseta Esposo",
  hasHealthIssues: "Problema de Sáude?",
  healthIssuesDescription: "Descrição de saúde",
  isPregnant: "Esposa grávida?",
  obs: "Obsersavação",
  pagamento_couponValue: "Cupom de desconto",
  pagamento_link_url: "Comprovante",
  pagamento_status: "Status de pagamento",
  pagamento_top_value: "Valor do evento",
  // add more fields
};

export const visibleColumnByEventType = {
  [ENUM_EVENT_TYPE.LEGENDARIOS]: {
    participate: "inscritos",
    serve: "lgndServir",
    checkinParticipate: "checkinParticipantes",
    checkinServe: "checkinLgnd",
    bone: "bone",
    family: "familia",
  },
  [ENUM_EVENT_TYPE.REM]: {
    participate: "inscritosRem",
    serve: "lgndServirRem",
    checkinParticipate: "checkinParticipantesRem",
    checkinServe: "checkinLgndRem",
    bone: "boneRem",
    family: "familiaRem",
  },
  [ENUM_EVENT_TYPE.LEGADO_FILHA]: {
    participate: "",
    serve: "",
    checkinParticipate: "",
    checkinServe: "",
    bone: "",
    family: "",
  },
  [ENUM_EVENT_TYPE.LEGADO_FILHO]: {
    participate: "",
    serve: "",
    checkinParticipate: "",
    checkinServe: "",
    bone: "",
    family: "",
  },
} as const;
