export enum ENUM_REGISTER_TYPE {
  PARTICIPANTE = "PARTICIPANTE",
  SERVIR = "SERVIR",
}

export enum ENUM_EVENT_TYPE {
  "LEGENDARIOS" = "LEGENDARIOS",
  "REM" = "REM",
  "LEGADO_FILHA" = "LEGADO_FILHA",
  "LEGADO_FILHO" = "LEGADO_FILHO",
  "MANADADAY" = "MANADADAY",
}

export enum ENUM_LGND_FUNCAO {
  DOC = "DOC",
  SUB_COORD_DOC = "SUB_COORD_DOC",
  COORDENADOR_DOC = "COORDENADOR_DOC",
  COORDENADOR_HAKUNA = "COORDENADOR_HAKUNA",
  SUB_COORD_HAKUNA = "SUB_COORD_HAKUNA",
  HAKUNA = "HAKUNA",
  COORDENADOR_AQUAMAN = "COORDENADOR_AQUAMAN",
  SUB_COORD_AQUAMAN = "SUB_COORD_AQUAMAN",
  AQUAMAN = "AQUAMAN",
  COORDENADOR_ADM = "COORDENADOR_ADM",
  SUB_COORD_ADM = "SUB_COORD_ADM",
  ADM = "ADM",
  COORDENADOR_SEGURANCA = "COORDENADOR_SEGURANCA",
  SUB_COORD_SEGURANCA = "SUB_COORD_SEGURANCA",
  INTERCESSAO = "INTERCESSAO",
  SUB_COORD_INTERCESSAO = "SUB_COORD_INTERCESSAO",
  COORDENADOR_INTERCESSAO = "COORDENADOR_INTERCESSAO",
  SEGURANCA = "SEGURANCA",
  COORDENADOR_EVENTOS = "COORDENADOR_EVENTOS",
  SUB_COORD_EVENTOS = "SUB_COORD_EVENTOS",
  EVENTOS = "EVENTOS",
  COORDENADOR_PATRON = "COORDENADOR_PATRON",
  SUB_COORD_PATRON = "SUB_COORD_PATRON",
  PATRON = "PATRON",
  COORDENADOR_LOGISTICA = "COORDENADOR_LOGISTICA",
  SUB_COORD_LOGISTICA = "SUB_COORD_LOGISTICA",
  LOGISTICA = "LOGISTICA",
  COORDENADOR_TARZAN = "COORDENADOR_TARZAN",
  SUB_COORD_TARZAN = "SUB_COORD_TARZAN",
  TARZAN = "TARZAN",
  COORDENADOR_DIRETOR = "COORDENADOR_DIRETOR",
  SUB_COORD_DIRETOR = "SUB_COORD_DIRETOR",
  DIRETOR = "DIRETOR",
  COORDENADOR_PREDICANTE = "COORDENADOR_PREDICANTE",
  SUB_COORD_PREDICANTE = "SUB_COORD_PREDICANTE",
  PREDICANTE = "PREDICANTE",
  COORDENADOR_EXTRACAO = "COORDENADOR_EXTRACAO",
  SUB_COORD_EXTRACAO = "SUB_COORD_EXTRACAO",
  EXTRACAO = "EXTRACAO",
  COORDENADOR_COMUNICACAO = "COORDENADOR_COMUNICACAO",
  SUB_COORD_COMUNICACAO = "SUB_COORD_COMUNICACAO",
  COMUNICACAO = "COMUNICACAO",
  COORDENADOR_MIDIA = "COORDENADOR_MIDIA",
  SUB_COORD_MIDIA = "SUB_COORD_MIDIA",
  MIDIA = "MIDIA",
  COORDENADOR_VOZ = "COORDENADOR_VOZ",
  SUB_COORD_VOZ = "SUB_COORD_VOZ",
  VOZ = "VOZ",
  COZINHA = "COZINHA",
  COORDENADOR_COZINHA = "COORDENADOR_COZINHA",
}

export enum ENUM_USER {
  USER = "USER",
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  LADIES = "LADIES",
  HAKUNA = "HAKUNA",
  CHECKIN = "CHECKIN",
}

export enum ENUM_STATUS {
  CONFIRMADA = "CONFIRMADA",
  INSCREVENDO = "INSCREVENDO",
  AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
  CANCELADA_PELO_CLIENTE = "CANCELADA_PELO_CLIENTE",
  CANCELADA_TEMPO_EXPIRADO = "CANCELADA_TEMPO_EXPIRADO",
}

export enum ENUM_CHECKIN_STATUS {
  WAITING_FOR_DOCUMENTS = "WAITING_FOR_DOCUMENTS",
  DOCUMENTS_SENT = "DOCUMENTS_SENT",
  INVALID_DOCUMENTS = "INVALID_DOCUMENTS",
  VALID_DOCUMENTS = "VALID_DOCUMENTS",
}

export enum ENUM_PAYMENT_STATUS {
  PAGAMENTO_CARTAO_PENDENTE = "PAGAMENTO_CARTAO_PENDENTE",
  CREDIT_CARD_PAYMENT_COMPLETED = "CREDIT_CARD_PAYMENT_COMPLETED",
  PAGAMENTO_CARTAO_CONCLUIDO = "PAGAMENTO_CARTAO_CONCLUIDO",
  CHARGE_CREATED = "CHARGE_CREATED",
  CHARGE_COMPLETED = "CHARGE_COMPLETED",
  TRANSACTION_REFUND_RECEIVED = "TRANSACTION_REFUND_RECEIVED",
  CHARGE_EXPIRED = "CHARGE_EXPIRED",
  GRATUITO = "GRATUITO",
}

export enum ENUM_VEHICLE_TYPE {
  CAR = "CAR",
  BUS = "BUS",
}
