export const eventToSecretKey: Record<string, string> = {
  "OPENPIX:CHARGE_CREATED": "WOOVI_HMAC_SECRET_KEY_CHARGE_CREATED",
  "OPENPIX:CHARGE_COMPLETED": "WOOVI_HMAC_SECRET_KEY_CHARGE_COMPLETED",
  "OPENPIX:CHARGE_EXPIRED": "WOOVI_HMAC_SECRET_KEY_CHARGE_EXPIRED",
  "OPENPIX:TRANSACTION_REFUND_RECEIVED":
    "WOOVI_HMAC_SECRET_KEY_TRANSACTION_REFUND_RECEIVED",
  // add more events here if needed
};
